### ISSUE TITLE
Bug with the EnumPicker editor script, preventing lists of effected enums

### ISSUE THREAD

**Issue by devyndamonster** [H3VR-Modding/MeatKit#16]
There is a bug withing the EnumPicker script which prevents you from creating lists of the effected enums in editor. When trying to add values to the list, an error is thrown in console and the list size remains at 0.

### Error in console
![enumError1](https://user-images.githubusercontent.com/6070388/164997041-0a7c731c-88f7-4738-932c-9f5624ae8026.png)

### Example script for reproducing the bug. The list of enums which are handled by EnumPicker do not work, and the ones not touched still work
![enumError2](https://user-images.githubusercontent.com/6070388/164997042-2d1a0c10-19b2-4f84-97a5-f2edb6e0ce85.png)
![enumError3](https://user-images.githubusercontent.com/6070388/164997045-a97be589-d7b1-4665-83b2-ddff5f0fbdf7.png)

### The only enum lists that don't work are the ones that EnumPicker touches
![enumError4](https://user-images.githubusercontent.com/6070388/164997049-0da910e7-256f-40e2-a833-e952e4c2e6dd.png)

**Comment by nrgill28** [comment]
Fixed. The EnumPicker was checking if the field was an array, but not if it was a List.
