### ISSUE TITLE
Error when building map twice

### ISSUE THREAD

**Issue by devyndamonster** [H3VR-Modding/MeatKit#2]
I get the following error when building a map, moving the procuced files, and then trying to build the map again

![builderror](https://user-images.githubusercontent.com/6070388/139597102-87e32da8-9bc8-4c14-a67d-d6370572ec00.PNG)

I have to close unity and reopen in order to build again

Steps to reproduce this:
- Build map using meatkit->build
- Move built files somewhere else
- Build map again

**Comment by nrgill28** [comment]
Still need to look into what causes this, I have seen it before but cannot reliably reproduce it myself. Most likely a file handle isn't being disposed of somewhere.

**Comment by nrgill28** [comment]
Pushed a commit which copies the player assembly to a temp file before reading it to hopefully prevent this in the future.
It's hard to reproduce still so I can't confirm the fix but eventually if there are no further reports of it then I'll consider this closed.
