### ISSUE TITLE
Gun Ripper Creating New Directory with every keystroke

### ISSUE THREAD

**Issue by fsce1** [H3VR-Modding/MeatKit#21]
This happens when i try to change the default output directory in the Gunripper tool.
Lets say i want to change it to Assets/Gun/Ripper, it will create a directory in Assets/G, Assets/Gu, Assets/Gun/R, Assets/Gun/Ri, and etc.
it does this every time i add a new letter to the field

**Comment by nrgill28** [comment]
Technically the gun ripper tool isn't a part of the base MeatKit project, it's from the OtherLoader package, but Devyn's fork doesn't have issues enabled. So @devyndamonster this one's for you.

**Comment by devyndamonster** [comment]
Oh my fork doesn't have issues enabled? Okay will fix. And yes I'm aware of this bug, will fix

**Comment by nrgill28** [comment]
Closing as this has been fixed in [v1.1.0 of the OtherLoader package](https://github.com/devyndamonster/MeatKit/releases/tag/OtherloaderPackage-1.1.0)
