### ISSUE TITLE
Problems importing prefabs using PrefabLoader

### ISSUE THREAD

**Issue by devyndamonster** [H3VR-Modding/MeatKit#5]
When trying to build a gun based off of a game prefab, script references on the prefab break when saving Unity, exiting, and reopening the project.

Before Reloading:
![tec9scripts](https://user-images.githubusercontent.com/6070388/144773195-2816cf2e-ac60-4bbb-95a8-92ff4507e73d.PNG)

After:
![scripts](https://user-images.githubusercontent.com/6070388/144772804-feb9b39d-fe1a-460b-a48b-78e0e1364c9f.PNG)

Steps to recreate:
- Import one of the games streaming asset bundles (I used the pistols bundle)
- Prefab load something from the bundle (I used the tec9 illegal version)
- With the gun spawned in the scene, script references should currently work
- Now drag the gun into your assets folder to make it a prefab
- Save Unity and exit
- Repopen Unity to find that your prefabs scripts are now all broken

**Comment by devyndamonster** [comment]
I'll add to this issue that by spawning the prefab while in Play/Pause mode, dragging the prefab into your assets folder, and then exiting play mode does work, and maintains the script references. If this is the intended way of doing things, then I think having the prefab loader work outside of play mode could confuse people

**Comment by nrgill28** [comment]
It isn't the intended way, although I am a bit confused to what Unity does differently in play/pause mode to make this happen. I'll have to look at the data that Unity is saving into the prefab that causes it to lose the reference after an editor restart.

**Comment by fsce1** [comment]
end user here, i quite commonly load things outside of play-pause mode in order to quickly see how some prefabs are set up without saving that prefab, it saves a lot of time instead of booting up VR every time i want a quick peek inside a prefab so id prefer if it still was possible to load things outside of pause/playmode <3

**Comment by nrgill28** [comment]
Closing - use the advanced prefab loader that comes with OL rather than the one in MeatKit.
